name: CodeGuru Reviewer (Pull Request)

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  codeguru-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Amazon CodeGuru Reviewer
      uses: aws-actions/codeguru-reviewer@main
      with:
        name: Hibrar/movies-and-shows-backend
        source_path: .
        build_path: .
        s3_bucket: codeguru-reviewer-hibrar-cicd
        source_branch: ${{ github.event.pull_request.head.ref }}
        destination_branch: ${{ github.event.pull_request.base.ref }}
        source_commit: ${{ github.event.pull_request.head.sha }}
        destination_commit: ${{ github.event.pull_request.base.sha }}
        output_format: SARIF
      env:
        AWS_REGION: eu-west-2
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
