name: codeguru-review

on:
  push:
    branches: [main]

jobs:
  codeguru-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run CodeGuru Reviewer
        uses: aws-actions/codeguru-reviewer@main
        with:
          name: ${{ github.repository }}
          source_path: .
          build_path: .
          s3_bucket: codeguru-review-demo-cicd
        env:
          AWS_REGION: eu-west-2
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
