name: Amazon CodeGuru Reviewer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  codeguru-review:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Amazon CodeGuru Reviewer
        uses: aws-actions/codeguru-reviewer@main
        with:
          build_path: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_REGION: eu-west-1  # Change to your region if needed
