name: codeguru-review

on:
  push:
    branches: [main]

jobs:
  codeguru-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run CodeGuru Reviewer (Full Repository Analysis)
        uses: aws-actions/codeguru-reviewer@main
        with:
          name: ${{ github.repository }}
          source_path: .
          build_path: .
          s3_bucket: codeguru-reviewer-hibrar-cicd
          args: FullRepositoryAnalysis
        env:
          AWS_REGION: eu-west-2
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
